# This is a basic workflow to help you get started with Actions

name: Trigger Integration Deployment script

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "beta", "stage", "preview" ]
    paths: ["Collection_Backups/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Fetch-depth 2 ensures we can access latest commit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set variables
        run: |
          collectionPath=$(echo $(git diff-tree --no-commit-id --name-only -r $GITHUB_REF))
          fileName=$(echo "$collectionPath" | sed -r "s/.+\/(.+)\..+/\1/")
          apiKeyVarName="secrets.${GITHUB_REF_NAME^^}_API_KEY"
          echo "integrationClassId=$fileName" >> $GITHUB_ENV
          echo "env=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "envCheck=${{ vars.REPO_VAR }}" >> $GITHUB_ENV
          echo ${!apiKeyVarName}
          echo "apiKey=${{ secrets.BETA_API_KEY }}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run deployment script
        run: |
          npm i
          node index.js -e $env -i $integrationClassId -k ${{ ${!apiKeyVarName} }}